version: "3.8"

networks:
  network:

volumes:
  source:
  data:

services:

  source:
    image: deathstar.source
    volumes:
      - type: volume
        source: source
        target: /ctx/DeathStarGame
        volume:
          nocopy: false
    networks:
      - network

  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.3.2
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    depends_on:
      - source
    networks:
      - network
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - type: volume
        source: source
        target: /ctx/DeathStarGame
        volume:
          nocopy: false
      # - ./traefik/traefik.toml:/etc/traefik/traefik.toml

  ipfs:
    image: ipfs/go-ipfs:latest
    ports:
      - 4001:4001
      - 127.0.0.1:5001:5001
      - 127.0.0.1:8088:8080
      - 127.0.0.1:8081:8081
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata
    depends_on:
      - source
    networks:
      - network
    volumes:
      - type: volume
        source: source
        target: /ctx/DeathStarGame
        volume:
          nocopy: true
      - type: volume
        source: data
        target: /ipfsdata
        volume:
          nocopy: true

  app:
    image: deathstar.app
    command: tail -f /dev/null
    ports:
      - 7788:7788
      - 8000:8080
    depends_on:
      - source
    networks:
      - network
    volumes:
      - type: volume
        source: source
        target: /ctx/DeathStarGame
        volume:
          nocopy: true
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M

  vscode:
    image: codercom/code-server:latest
    ports:
      - 8800:8080
    command: --auth none
    depends_on:
      - source
    networks:
      - network
    volumes:
      - type: volume
        source: source
        target: /ctx/DeathStarGame
        volume:
          nocopy: true

  # cljs-compiler:
  #   image: deathstar.cljs-compiler
  #   volumes:
  #     - ./ui/.user:/root
  #     - ./ui:/ctx/bin/ui
  #     - ../src:/ctx/src
  #   build:
  #     context: ./ui
  #     dockerfile: ./dev.Dockerfile
  #     args:
  #       workdir: /ctx/bin/ui
  #   command: tail -f /dev/null
  #   # command: bash f dev
  #   ports:
  #     - 8899:8899
  #     - 9630:9630
  #     - 9500:9500
  #   stdin_open: true
  #   tty: true
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '4'
  #         memory: 4096M

  # game-ui:
  #   image: deathstar.game-ui
  #   expose:
  #     - 80
  #   stdin_open: true
  #   tty: true
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '4'
  #         memory: 4096M

